version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - ${VOLUME_PATH}/db:/var/lib/mysql
     ports:
       - "${MYSQL_PORT}:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - '80'
       - '443'
     restart: always
     environment:
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
       WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
       WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
       WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
       VIRTUAL_HOST: ${VIRTUAL_HOST}
      #  VIRTUAL_PROTO: https
      #  VIRTUAL_PORT: 443
       LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
     volumes:
       - ${VOLUME_PATH}/site:/var/www/html/
   #
  #  cli:
  #    image: wordpress:cli
  #    volumes_from:
  #      - wordpress

networks:
    default:
       external:
         name: v3_default